export const data = [
  {
    id: 1,
    firstName: "Nguyễn",
    lastName: "Văn An",
    phone: "0123456789",
    email: "nguyen.van.an@email.com",
    address: "123 Nguyễn Trãi, Hà Nội",
    company: "Công ty ABC",
    category: "Công Việc",
  },
  {
    id: 2,
    firstName: "Trần",
    lastName: "Thị Bình",
    phone: "0987654321",
    email: "tran.thi.binh@email.com",
    address: "456 Lê Lợi, TP.HCM",
    company: "Công ty XYZ",
    category: "Gia Đình",
  },
  {
    id: 3,
    firstName: "Lê",
    lastName: "Minh Cường",
    phone: "0369852147",
    email: "le.minh.cuong@email.com",
    address: "789 Trần Hưng Đạo, Đà Nẵng",
    company: "Freelancer",
    category: "Bạn Bè",
  },
  {
    id: 4,
    firstName: "Phạm",
    lastName: "Thanh Tùng",
    phone: "0912345678",
    email: "pham.thanh.tung@email.com",
    address: "12 Nguyễn Huệ, Huế",
    company: "Công ty 123",
    category: "Công Việc",
  },
  {
    id: 5,
    firstName: "Vũ",
    lastName: "Thị Mai",
    phone: "0945671234",
    email: "vu.thi.mai@email.com",
    address: "34 Hoàng Hoa Thám, Hải Phòng",
    company: "Startup XYZ",
    category: "Bạn Bè",
  },
];
