export const data = [
  {
    id: 1,
    code: "SV1010",
    fullName: "Lục Văn Thuận",
    email: "lucthuan123@gmail.com",
    gender: "Nam",
    dob: "2004-05-01",
    notes: "Học lực giỏi",
  },
  {
    id: 2,
    code: "SV1011",
    fullName: "Lưu Minh Quân",
    email: "quanexe456@gmail.com",
    gender: "Nam",
    dob: "2005-12-05",
    notes: "Tham gia CLB bóng đá",
  },
  {
    id: 3,
    code: "SV1012",
    fullName: "Nguyễn Thị Hồng",
    email: "hongnguyen789@gmail.com",
    gender: "Nữ",
    dob: "2003-08-14",
    notes: "Học lực khá",
  },
  {
    id: 4,
    code: "SV1013",
    fullName: "Phạm Văn An",
    email: "anpham321@gmail.com",
    gender: "Nam",
    dob: "2004-11-20",
    notes: "Đang thực tập",
  },
  {
    id: 5,
    code: "SV1014",
    fullName: "Trần Thị Mai",
    email: "maitran654@gmail.com",
    gender: "Nữ",
    dob: "2005-02-18",
    notes: "Tham gia CLB tiếng Anh",
  },
  {
    id: 6,
    code: "SV1015",
    fullName: "Hoàng Văn Tú",
    email: "tuhoang987@gmail.com",
    gender: "Nam",
    dob: "2004-06-30",
    notes: "Học lực xuất sắc",
  },
  {
    id: 7,
    code: "SV1016",
    fullName: "Ngô Thị Lan",
    email: "lanngo456@gmail.com",
    gender: "Nữ",
    dob: "2003-09-25",
    notes: "Tham gia CLB múa",
  },
  {
    id: 8,
    code: "SV1017",
    fullName: "Đặng Văn Hoàng",
    email: "hoangdang123@gmail.com",
    gender: "Nam",
    dob: "2005-03-10",
    notes: "Học lực trung bình",
  },
  {
    id: 9,
    code: "SV1018",
    fullName: "Bùi Thị Thảo",
    email: "thaobui321@gmail.com",
    gender: "Nữ",
    dob: "2004-07-07",
    notes: "Tham gia đội tình nguyện",
  },
];
